# Generated by Django 3.0.6 on 2020-05-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='item',
            field=models.TextField(blank=True),
        ),
    ]
